version: '3.7'

services:
  neo4j:
    image: neo4j:4.0-enterprise
    container_name: "covid-graph"
    volumes:
      - ./plugins:/plugins
      - ./data-4.0:/data
      - ./import:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_AUTH=neo4j/neo"
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*"
      - NEO4J_dbms_directories_import=import
      # - NEO4JLABS_PLUGINS=["apoc"]
